---
- hosts: [all]
  become: yes
  tasks:
    - name: Clone repo with docker-compose file
      command: git clone https://github.com/dima-frost/pyapp.git
    - name: Run "docker-compose up"
      command: docker-compose --file ./pyapp/docker-compose.yaml up -d